apiVersion: v1
kind: Pod
metadata:
  name: ejemplo 
spec:
  containers:
    - name: ejemplo 
      image: apasoft/web1
  imagePullSecrets:
    - name : midocker

##o de manera declarativa tambien colocando las credenciales kubectl  ajecutar create secret docker-registry midocker --docker-serve=docker.io --docker-username=jhonajm docker-password=password --docker-email=jho.jim.01@gmail.com